apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-api-gateway-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    ci.taskflow.io/last-built-sha: ce74e7c052fda1eac9faa5679e30a63ff8aa87fe
    ci.taskflow.io/last-built-at: "2026-04-28T11:56:07Z"
    ci.taskflow.io/last-built-by: Thanu-sri1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/project-taskflow/taskflow.git
    targetRevision: main
    path: helm
    helm:
      releaseName: taskflow-api-gateway-dev
      valueFiles:
        - values.yaml
      values: |
        configMap:
          enabled: false
        secret:
          enabled: false
        storageClass:
          enabled: false
        gateway:
          enabled: false
        httpRoute:
          enabled: false
        mongo:
          statefulSet:
            enabled: false
          service:
            enabled: false
        authService:
          enabled: false
        userService:
          enabled: false
        taskService:
          enabled: false
        notificationService:
          enabled: false
        analyticsService:
          enabled: false
        apiGateway:
          enabled: true
          image: ghcr.io/project-taskflow/api-gateway:ce74e7c052fda1eac9faa5679e30a63ff8aa87fe
        frontend:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
