apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-notification-service-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    ci.smartparking.io/last-built-sha: ce1502b6cd4f0722c087709b3fec08f19483474a
    ci.smartparking.io/last-built-at: "2026-04-28T11:36:47Z"
    ci.smartparking.io/last-built-by: Thanu-sri1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/project-taskflow/taskflow.git
    targetRevision: main
    path: helm
    helm:
      releaseName: taskflow-notification-service-dev
      valueFiles:
        - values.yaml
      values: |
        configMap:
          enabled: false
        secret:
          enabled: false
        storageClass:
          enabled: false
        gateway:
          enabled: false
        httpRoute:
          enabled: false
        mongo:
          statefulSet:
            enabled: false
          service:
            enabled: false
        authService:
          enabled: false
          image: ghcr.io/project-taskflow/auth-service:889cb92f581e5aa51602310cacfc435921fd661a
        userService:
          enabled: false
        taskService:
          enabled: false
        notificationService:
          enabled: true
          image: ghcr.io/project-taskflow/notification-service:ce1502b6cd4f0722c087709b3fec08f19483474a
        analyticsService:
          enabled: false
        apiGateway:
          enabled: false
        frontend:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
