apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-task-service-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    ci.smartparking.io/last-built-sha: 5c5bd44bb73289417bacb352132356c724510d5a
    ci.smartparking.io/last-built-at: "2026-04-28T11:25:19Z"
    ci.smartparking.io/last-built-by: Thanu-sri1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/project-taskflow/taskflow.git
    targetRevision: main
    path: helm
    helm:
      releaseName: taskflow-task-service-dev
      valueFiles:
        - values.yaml
      values: |
        configMap:
          enabled: false
        secret:
          enabled: false
        storageClass:
          enabled: false
        gateway:
          enabled: false
        httpRoute:
          enabled: false
        mongo:
          statefulSet:
            enabled: false
          service:
            enabled: false
        authService:
          enabled: false
        userService:
          enabled: false
        taskService:
          enabled: true
          image: ghcr.io/project-taskflow/task-service:5c5bd44bb73289417bacb352132356c724510d5a
        notificationService:
          enabled: false
        analyticsService:
          enabled: false
        apiGateway:
          enabled: false
        frontend:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
