apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-user-service-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    ci.taskflow.io/last-release-sha: 501f6c171a1af4ae8e15e33a1ffd0f9ca9f42f89
    ci.taskflow.io/last-release-tag: v1.1.6
    ci.taskflow.io/last-released-at: "2026-04-28T09:45:21Z"
    ci.taskflow.io/last-released-by: Thanu-sri1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/project-taskflow/taskflow.git
    targetRevision: main
    path: helm
    helm:
      releaseName: taskflow-user-service-prod
      valueFiles:
        - values-prod.yaml
      values: |
        configMap:
          enabled: false
        secret:
          enabled: false
        storageClass:
          enabled: false
        gateway:
          enabled: false
        httpRoute:
          enabled: false
        mongo:
          statefulSet:
            enabled: false
          service:
            enabled: false
        authService:
          enabled: false
        userService:
          enabled: true
          image: ghcr.io/project-taskflow/user-service:v1.1.6
        taskService:
          enabled: false
        notificationService:
          enabled: false
        analyticsService:
          enabled: false
        apiGateway:
          enabled: false
        frontend:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
